
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    k8s.renderer/template-version: 1.0.0
    k8s.renderer/commit: bc09c82448d5b0263a657864b2d88c079bd34d19
    k8s.renderer/branch: refs/heads/main
    k8s.renderer/vcs-url: matiasmartin-labs/auth-ms
    k8s.renderer/render-time: 2025-05-02T21:50:03Z
  labels:
    app.kubernetes.io/name: auth-ms
    app.kubernetes.io/part-of: auth-system
    app.kubernetes.io/version: v2.1.1
    app.kubernetes.io/managed-by: k8s.renderer
  name: auth-ms
  namespace: matiasmartin-labs
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: auth-ms
      app.kubernetes.io/part-of: auth-system
  template:
    metadata:
      annotations:
        k8s.renderer/template-version: 1.0.0
        k8s.renderer/commit: bc09c82448d5b0263a657864b2d88c079bd34d19
        k8s.renderer/branch: refs/heads/main
        k8s.renderer/vcs-url: matiasmartin-labs/auth-ms
        k8s.renderer/render-time: 2025-05-02T21:50:03Z
      labels:
        app.kubernetes.io/name: auth-ms
        app.kubernetes.io/part-of: auth-system
        app.kubernetes.io/version: v2.1.1
        app.kubernetes.io/managed-by: k8s.renderer
      namespace: matiasmartin-labs
    spec:
      containers:
        - envFrom: 
            - secretRef:
                name: psql-credentials 
          image: ghcr.io/matiasmartin-labs/auth-ms:v2.1.1
          imagePullPolicy: Always
          name: auth-ms
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          volumeMounts: 
            - mountPath: /etc/keys
              name: jwt-keys-volume
              readOnly: true 
      imagePullSecrets:
        - name: ghcr-secret
      volumes: 
        - name: jwt-keys-volume
          secret:
            defaultMode: 420
            optional: false
            secretName: jwt-keys  
