
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    k8s.renderer/template-version: 1.0.0
    k8s.renderer/commit: 7113c223249b1570503498369e91a77a7e07545d
    k8s.renderer/branch: refs/tags/v1.0.2
    k8s.renderer/vcs-url: matiasmartin-labs/auth-ms
    k8s.renderer/render-time: 2025-04-27T19:53:33Z
  labels:
    app.kubernetes.io/name: auth-ms
    app.kubernetes.io/part-of: auth-system
    app.kubernetes.io/version: v1.0.2
    app.kubernetes.io/managed-by: k8s.renderer
  name: auth-ms
  namespace: matiasmartin-labs
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: auth-ms
      app.kubernetes.io/part-of: auth-system
      app.kubernetes.io/version: v1.0.2
  template:
    metadata:
      annotations:
        k8s.renderer/template-version: 1.0.0
        k8s.renderer/commit: 7113c223249b1570503498369e91a77a7e07545d
        k8s.renderer/branch: refs/tags/v1.0.2
        k8s.renderer/vcs-url: matiasmartin-labs/auth-ms
        k8s.renderer/render-time: 2025-04-27T19:53:33Z
      labels:
        app.kubernetes.io/name: auth-ms
        app.kubernetes.io/part-of: auth-system
        app.kubernetes.io/version: v1.0.2
        app.kubernetes.io/managed-by: k8s.renderer
      namespace: matiasmartin-labs
    spec:
      containers:
        - envFrom: 
            - secretRef:
                name: psql-credentials 
          image: ghcr.io/matiasmartin-labs/auth-ms:v1.0.2
          imagePullPolicy: Always
          name: auth-ms
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          volumeMounts: 
            - mountPath: /etc/keys
              name: jwt-keys-volume
              readOnly: true 
      imagePullSecrets:
        - name: ghcr-secret
      volumes: 
        - name: jwt-keys-volume
          secret:
            defaultMode: 420
            optional: false
            secretName: jwt-keys  
