apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    k8s.renderer/template-version: 1.0.0
    k8s.renderer/commit: d99e0a6e48dbc3b1a333b3bda0a9c274f6a6513e
    k8s.renderer/branch: refs/tags/v2.5.0
    k8s.renderer/vcs-url: matiasmartin-labs/auth-ms
    k8s.renderer/render-time: 2025-05-03T20:08:01Z
  labels:
    app.kubernetes.io/name: auth-ms
    app.kubernetes.io/part-of: auth-system
    app.kubernetes.io/version: v2.5.0
    app.kubernetes.io/managed-by: k8s.renderer
    release: monitoring
  name: auth-ms
  namespace: matiasmartin-labs
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: auth-ms
      app.kubernetes.io/part-of: auth-system
      app.kubernetes.io/version:  v2.5.0
  endpoints:
    - port: http
      path: /q/metrics
      interval: 30s
      targetPort: 8080
  namespaceSelector:
    matchNames:
      - matiasmartin-labs
