apiVersion: v1
kind: Service
metadata:
  annotations:
    k8s.renderer/template-version: 1.0.0
    k8s.renderer/commit: 4a5c3ed32fb80d5e52a7a7088f5864ff48908a17
    k8s.renderer/branch: refs/heads/main
    k8s.renderer/vcs-url: matiasmartin-labs/auth-ms
    k8s.renderer/render-time: 2025-05-02T22:29:41Z
  labels:
    app.kubernetes.io/name: auth-ms
    app.kubernetes.io/part-of: auth-system
    app.kubernetes.io/version: v2.2.0
    app.kubernetes.io/managed-by: k8s.renderer
  name: auth-ms
  namespace: matiasmartin-labs
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: auth-ms
    app.kubernetes.io/part-of: auth-system
    app.kubernetes.io/version:  v2.2.0