app:
  name: auth-ms
  port: 8080
  part-of: auth-system
  replicas: 1

namespace: matiasmartin-labs

network:
  host: auth-ms.raspisrv.local

mounts:
  - name: jwt-keys-volume
    mount-path: /etc/keys
    read-only: true

secret-volumes:
  - name: jwt-keys-volume
    default-mode: 420
    secret-name: jwt-keys

env:
  secrets:
    - psql-credentials
