app:
  name: auth-ms
  port: 8080
  part-of: auth-system
  replicas: 1
  metrics:
    path: /q/metrics
  health-check:
    liveness:
      path: /q/health/live
      initial-delay-seconds: 5
    readiness:
      path: /q/health/ready
      initial-delay-seconds: 10
  resources:
    limits:
      memory: 30Mi
      cpu: 250m
    requests:
      memory: 20Mi
      cpu: 50m

namespace: matiasmartin-labs

network:
  host: auth-ms.raspisrv.local

mounts:
  - name: jwt-keys-volume
    mount-path: /etc/keys
    read-only: true

secret-volumes:
  - name: jwt-keys-volume
    default-mode: 420
    secret-name: jwt-keys

env:
  secrets:
    - psql-credentials
