name: build-native-and-promotes

on:
  release:
    types:
      - created

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  build:
    name: Build native and push image
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java & GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Maven wrapper
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            .mvn/wrapper
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build native image
        run: |
          RELEASE_TAG="${{ github.event.release.tag_name }}"

          ./mvnw clean install -Pnative -DskipTests -Dquarkus.container-image.tag=$RELEASE_TAG

  promote:
    name: Promote k8s manifests
    runs-on: ubuntu-24.04-arm
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: K8S Renderer
        uses: matiasmartin-labs/gha-deployments/k8s-renderer@main
        with:
          input-dir: ./k8s
          output-dir: ./k8s/manifests
          log-level: debug
          version: ${{ github.event.release.tag_name }}
          docker-registry: ghcr.io/matiasmartin-labs
          image-pull-secret: ghcr-secret

      - name: Git Config
        run: |
          git config --global user.name "Action"
          git config --global user.email "action@github.com"

      - name: Checkout k8s-manifests branch
        run: |
          git fetch origin k8s-manifests
          git switch k8s-manifests
          
          git checkout -b "deploy-pr-${{ github.event.release.tag_name }}"

      - name: Move manifests to root directory
        run: |
          mv ./k8s/manifests/* ./

      - name: Create a PR for the manifests
        uses: peter-evans/create-pull-request@v7
        with:
          title: Promote Kubernetes Manifests for version ${{ github.event.release.tag_name }}
          body: This PR adds Kubernetes manifests for version ${{ github.event.release.tag_name }}.
          base: k8s-manifests
          branch: deploy-pr-${{ github.event.release.tag_name }}
          commit-message: Promote Kubernetes manifests for version ${{ github.event.release.tag_name }}