name: build-native-and-promotes

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version: ex. v2.0.0'
        required: true
  release:
    types:
      - created

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  build:
    name: Build native and push image
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java & GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Maven wrapper
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            .mvn/wrapper
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Get release tag or dispatch input
        id: resolve-tag
        run: |
          TAG="${{ github.event.release.tag_name }}"
          if [ -z "$TAG" ]; then
            TAG="${{ github.event.inputs.version }}"
          fi
          echo "Resolved tag: $TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Build native image
        run: |
          RELEASE_TAG="${{ steps.resolve-tag.outputs.tag }}"

          ./mvnw clean install -Pnative -DskipTests -Dquarkus.container-image.tag=$RELEASE_TAG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_USERNAME: ${{ github.actor }}
          MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

  promote:
    name: Promote k8s manifests
    runs-on: ubuntu-24.04-arm
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get release tag or dispatch input
        id: resolve-tag
        run: |
          TAG="${{ github.event.release.tag_name }}"
          if [ -z "$TAG" ]; then
            TAG="${{ github.event.inputs.version }}"
          fi
          echo "Resolved tag: $TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: K8S Renderer
        uses: matiasmartin-labs/gha-deployments/k8s-renderer@main
        with:
          input-dir: ./k8s
          output-dir: ./k8s/manifests
          log-level: debug
          version: ${{ steps.resolve-tag.outputs.tag }}
          docker-registry: ghcr.io/matiasmartin-labs
          image-pull-secret: ghcr-secret

      - name: Git Config
        run: |
          git config --global user.name "Action"
          git config --global user.email "action@github.com"

      - name: Checkout k8s-manifests branch
        run: |
          git fetch origin k8s-manifests
          git switch k8s-manifests
          
          git checkout -b "deploy-pr-${{ steps.resolve-tag.outputs.tag }}"

      - name: Move manifests to root directory
        run: |
          mv ./k8s/manifests/* ./
          rm -r ./k8s

      - name: Commit and Push manifests
        run: |
          git add ./*.yml
          git commit -m "Promote Kubernetes manifests for version ${{ steps.resolve-tag.outputs.tag }}"
          git push origin "deploy-pr-${{ steps.resolve-tag.outputs.tag }}"

      - name: Create a PR for the manifests
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --title "Promote Kubernetes Manifests for version ${{ steps.resolve-tag.outputs.tag }}" \
            --body "This PR adds Kubernetes manifests for version ${{ steps.resolve-tag.outputs.tag }}." \
            --base k8s-manifests \
            --head "deploy-pr-${{ steps.resolve-tag.outputs.tag }}" \
            --repo ${{ github.repository }}