name: release-preview

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - labeled

jobs:
  preview:
    if: (
      github.event.pull_request.base.ref == 'main') && (
      contains(join(github.event.pull_request.labels.*.name, ','), 'release-type/patch') ||
      contains(join(github.event.pull_request.labels.*.name, ','), 'release-type/minor') ||
      contains(join(github.event.pull_request.labels.*.name, ','), 'release-type/major')
      )
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set release type
        id: set_release_type
        run: |
          if echo "${{ toJson(github.event.pull_request.labels) }}" | grep -q 'release-type/major'; then
            echo "type=major" >> $GITHUB_OUTPUT
          elif echo "${{ toJson(github.event.pull_request.labels) }}" | grep -q 'release-type/minor'; then
            echo "type=minor" >> $GITHUB_OUTPUT
          elif echo "${{ toJson(github.event.pull_request.labels) }}" | grep -q 'release-type/patch'; then
            echo "type=patch" >> $GITHUB_OUTPUT
          else
            echo "No release-type label found."
            exit 1
          fi

      - name: Calculate next version
        id: calculate_version
        uses: matiasmartin-labs/gha-deployments/calculate-mvn-version@main
        with:
          release-type: ${{ steps.set_release_type.outputs.type }}

      - name: Comment on PR
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            🚀 Next version calculated: **${{ steps.calculate_version.outputs.new-version }}**
