name: release-preview

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - labeled

jobs:
  generate-preview:
    if: (
      github.event.pull_request.base.ref == 'main') && (
      contains(join(github.event.pull_request.labels.*.name, ','), 'release-type/patch') ||
      contains(join(github.event.pull_request.labels.*.name, ','), 'release-type/minor') ||
      contains(join(github.event.pull_request.labels.*.name, ','), 'release-type/major')
      )
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Determine release type
        uses: matiasmartin-labs/gha-deployments/determine-release-type@main
        id: release_type

      - name: Calculate next version
        id: calculate_version
        uses: matiasmartin-labs/gha-deployments/calculate-mvn-version@main
        with:
          release-type: ${{ steps.release_type.outputs.type }}

      - name: Generate changelog
        id: changelog
        run: |
          echo "body=$(git log --pretty=format:'- %s' origin/main..HEAD)" >> $GITHUB_OUTPUT

      - name: Comment on PR
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            # 🎉 Release Preview

            ## 🚀 Next Version
            ![Version](https://img.shields.io/badge/version-${{ steps.calculate_version.outputs.new-version }}-brightgreen)
            
            ## 📋 Changelog
            ${{ steps.changelog.outputs.body }}
