name: Release Preview

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - labeled

jobs:
  preview:
    if: (
      github.event.pull_request.base.ref == 'main') && (
      contains(join(github.event.pull_request.labels.*.name, ','), 'release-type/patch') ||
      contains(join(github.event.pull_request.labels.*.name, ','), 'release-type/minor') ||
      contains(join(github.event.pull_request.labels.*.name, ','), 'release-type/major')
      )
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print PR Info
        run: |
          echo "Pull Request ID: ${{ github.event.pull_request.number }}"
          echo "PR Target Branch: ${{ github.event.pull_request.base.ref }}"
          echo "Triggered by PR targeting main branch."